# Generated by Django 5.2.6 on 2025-09-10 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['slug', 'language'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='page',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='URL Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
