# Generated by Django 5.2.6 on 2025-09-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_page_options_remove_page_createdat_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug', 'language')},
        ),
    ]
