# Generated by Django 5.2.7 on 2025-11-27 10:39

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_page_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["slug"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="page",
            name="content_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="page",
            name="content_fr",
            field=tinymce.models.HTMLField(null=True, verbose_name="Content"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.RemoveField(
            model_name="page",
            name="language",
        ),
    ]
