# Generated by Django 5.2.7 on 2025-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_page_options_alter_page_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="slug_en",
            field=models.SlugField(null=True, unique=True, verbose_name="URL Slug"),
        ),
        migrations.AddField(
            model_name="page",
            name="slug_fr",
            field=models.SlugField(null=True, unique=True, verbose_name="URL Slug"),
        ),
    ]
