# Generated by Django 5.2.8 on 2025-12-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_page_slug_en_page_slug_fr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Page",
        ),
    ]
