# Generated by Django 5.2.9 on 2025-12-25 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_package_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("first_visit", models.BooleanField(verbose_name="First visit")),
                (
                    "traveling_with",
                    models.CharField(max_length=20, verbose_name="Traveling with"),
                ),
                ("interests", models.JSONField(verbose_name="Interests")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
