# Generated by Django 5.2.7 on 2025-11-10 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('guard', 'UserProfile')

    for user in User.objects.all():
        user_type = 'staff' if user.is_staff else 'client_partner'
        UserProfile.objects.get_or_create(
            user=user,
            defaults={'user_type': user_type},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('staff', 'Staff'), ('client_partner', 'Client / Partenaire')], default='client_partner', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.RunPython(create_existing_profiles, migrations.RunPython.noop),
    ]
