# Generated by Django 5.2.7 on 2025-11-10 13:45

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def seed_subscription_placeholders(apps, schema_editor):
    UserProfile = apps.get_model("guard", "UserProfile")
    today = timezone.now().date()
    default_renewal = today + timedelta(days=30)
    for profile in UserProfile.objects.all():
        updates = {}
        if not profile.subscription_started_at:
            updates["subscription_started_at"] = today
        if not profile.subscription_renews_at:
            updates["subscription_renews_at"] = default_renewal
        if updates:
            for field, value in updates.items():
                setattr(profile, field, value)
            profile.save(update_fields=list(updates.keys()))


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_plan",
            field=models.CharField(
                blank=True,
                default="Trial",
                help_text="Placeholder until Konnect subscription is attached.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_renews_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_started_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_status",
            field=models.CharField(blank=True, default="trial", max_length=32),
        ),
        migrations.RunPython(seed_subscription_placeholders, migrations.RunPython.noop),
    ]
