# Generated by Django 5.2.7 on 2025-11-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0003_location_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
    ]
