# Generated by Django 5.2.7 on 2025-11-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0004_remove_image_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="user",
        ),
    ]
