# Generated by Django 5.2.7 on 2025-11-27 15:53

import guard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0005_remove_location_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_mobile",
            field=models.ImageField(
                blank=True, null=True, upload_to=guard.models.location_image_path
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=guard.models.location_image_path),
        ),
    ]
