# Generated by Django 5.2.8 on 2025-11-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        ("guard", "0006_image_image_mobile_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="cities_light.city",
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="cities_light.country",
                verbose_name="Country",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="cities_light.region",
                verbose_name="Region/State",
            ),
        ),
    ]
