# Generated by Django 5.2.8 on 2025-11-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0007_location_city_location_country_location_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="region",
        ),
    ]
