# Generated by Django 5.2.8 on 2025-11-28 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0009_locationcategory_location_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="guard.locationcategory",
                verbose_name="Category",
            ),
        ),
    ]
