# Generated by Django 5.2.8 on 2025-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0010_alter_location_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationcategory",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="locationcategory",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
