# Generated by Django 5.2.8 on 2025-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0011_locationcategory_name_en_locationcategory_name_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="admissionFee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Admission Fee",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="openFrom",
            field=models.TimeField(blank=True, null=True, verbose_name="Open From"),
        ),
        migrations.AddField(
            model_name="location",
            name="openTo",
            field=models.TimeField(blank=True, null=True, verbose_name="Open To"),
        ),
    ]
