# Generated by Django 5.2.8 on 2025-12-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0012_location_admissionfee_location_openfrom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="admissionFee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Add admission fee if the location has a specific admission fee",
                max_digits=10,
                null=True,
                verbose_name="Admission Fee",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="openFrom",
            field=models.TimeField(
                blank=True,
                help_text="Add opening hours if the location is open from a specific time",
                null=True,
                verbose_name="Open From",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="openTo",
            field=models.TimeField(
                blank=True,
                help_text="Add opening hours if the location is open to a specific time",
                null=True,
                verbose_name="Open To",
            ),
        ),
    ]
