# Generated by Django 5.2.8 on 2025-12-03 11:22

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0013_alter_location_admissionfee_alter_location_openfrom_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ImageLocation",
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("startDate", models.DateField(verbose_name="Start Date")),
                ("endDate", models.DateField(verbose_name="End Date")),
                ("time", models.TimeField(verbose_name="Time")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("description", tinymce.models.HTMLField(verbose_name="Description")),
                ("image", models.ImageField(upload_to="location_image_path")),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="guard.userprofile",
                        verbose_name="Client",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="guard.location",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
    ]
