# Generated by Django 5.2.8 on 2025-12-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0014_rename_image_imagelocation_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagelocation",
            options={
                "verbose_name": "Location Image",
                "verbose_name_plural": "Location Images",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.AlterField(
            model_name="imagelocation",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="imagelocation",
            name="image_mobile",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.CreateModel(
            name="ImageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "image_mobile",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="guard.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Image",
                "verbose_name_plural": "Event Images",
            },
        ),
    ]
