# Generated by Django 5.2.8 on 2025-12-04 12:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0015_alter_imagelocation_options_remove_event_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_en",
            field=tinymce.models.HTMLField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="event",
            name="description_fr",
            field=tinymce.models.HTMLField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="event",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
