# Generated by Django 5.2.8 on 2025-12-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0018_alter_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="guard.eventcategory",
                verbose_name="Category",
            ),
            preserve_default=False,
        ),
    ]
