# Generated by Django 5.2.8 on 2025-12-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0019_alter_event_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={
                "verbose_name": "Event Category",
                "verbose_name_plural": "Event Categories",
            },
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
