# Generated by Django 5.2.8 on 2025-12-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0020_alter_eventcategory_options_eventcategory_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_fr", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "Tip",
                "verbose_name_plural": "Tips",
            },
        ),
    ]
