# Generated by Django 5.2.8 on 2025-12-16 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        ("guard", "0021_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tips",
                to="cities_light.city",
                verbose_name="Cities",
            ),
        ),
    ]
