# Generated by Django 5.2.8 on 2025-12-16 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        ("guard", "0022_tip_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hiking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                (
                    "name_fr",
                    models.CharField(max_length=255, null=True, verbose_name="Name"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "description_fr",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hikings",
                        to="cities_light.city",
                        verbose_name="Cities",
                    ),
                ),
                (
                    "location",
                    models.ManyToManyField(
                        to="guard.location", verbose_name="Location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hiking",
                "verbose_name_plural": "Hikings",
            },
        ),
        migrations.CreateModel(
            name="ImageHiking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "image_mobile",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hiking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="guard.hiking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hiking Image",
                "verbose_name_plural": "Hiking Images",
            },
        ),
    ]
