# Generated by Django 5.2.8 on 2025-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0023_hiking_imagehiking"),
    ]

    operations = [
        migrations.AddField(
            model_name="tip",
            name="location",
            field=models.ManyToManyField(to="guard.location", verbose_name="Location"),
        ),
    ]
