# Generated by Django 5.2.8 on 2025-12-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0024_tip_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="ads/")),
                ("link", models.URLField()),
                ("short_link", models.URLField(blank=True, null=True)),
                ("short_id", models.CharField(blank=True, max_length=50, null=True)),
                ("clicks", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ad",
                "verbose_name_plural": "Ads",
            },
        ),
        migrations.CreateModel(
            name="ImageAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "image_mobile",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="guard.ad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Image",
                "verbose_name_plural": "Ad Images",
            },
        ),
    ]
