# Generated by Django 5.2.8 on 2025-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0025_ad_imagead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.AddField(
            model_name='ad',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Size: 320x50 pixels', null=True, upload_to='ads/mobile/', verbose_name='Mobile Image (320x50)'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_tablet',
            field=models.ImageField(blank=True, help_text='Size: 728x90 pixels', null=True, upload_to='ads/tablet/', verbose_name='Tablet Image (728x90)'),
        ),
    ]
