# Generated by Django 5.2.8 on 2025-12-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0026_remove_ad_image_ad_image_mobile_ad_image_tablet"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="guard.userprofile",
                verbose_name="User",
            ),
        ),
    ]
