# Generated by Django 5.2.8 on 2025-12-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0027_ad_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="user",
        ),
        migrations.AddField(
            model_name="ad",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="guard.userprofile",
                verbose_name="Client",
            ),
        ),
    ]
