# Generated by Django 5.2.8 on 2025-12-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0028_remove_ad_user_ad_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link",
            field=models.URLField(default="https://www.fielmedina.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="short_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="short_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
