# Generated by Django 5.2.8 on 2025-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0029_event_link_event_short_id_event_short_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.URLField(verbose_name="The link to subscribe"),
        ),
    ]
