# Generated by Django 5.2.8 on 2025-12-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0030_alter_event_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Add a name"
            ),
        ),
    ]
