# Generated by Django 5.2.8 on 2025-12-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0031_ad_name"),
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="shared.userprofile",
                verbose_name="Client",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="shared.userprofile",
                verbose_name="Client",
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
