# Generated by Django 5.2.8 on 2025-12-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        ("guard", "0032_alter_event_client_alter_ad_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="cities_light.city",
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="cities_light.city",
                verbose_name="City",
            ),
        ),
    ]
