# Generated by Django 5.2.8 on 2025-12-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        ("guard", "0033_ad_city_event_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicTransports",
                        to="cities_light.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "fromRegion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicTransportsFromRegion",
                        to="cities_light.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "toRegion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicTransportsToRegion",
                        to="cities_light.region",
                        verbose_name="Region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Transport",
                "verbose_name_plural": "Public Transports",
            },
        ),
        migrations.CreateModel(
            name="PublicTransportTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time", models.TimeField(verbose_name="Time")),
                (
                    "publicTransport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicTransportTimes",
                        to="guard.publictransport",
                        verbose_name="Public Transport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Transport Time",
                "verbose_name_plural": "Public Transport Times",
            },
        ),
    ]
