# Generated by Django 5.2.8 on 2025-12-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        ("guard", "0035_alter_publictransport_fromregion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publictransport",
            name="fromRegion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicTransportsFromRegion",
                to="cities_light.subregion",
                verbose_name="From region",
            ),
        ),
        migrations.AlterField(
            model_name="publictransport",
            name="toRegion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publicTransportsToRegion",
                to="cities_light.subregion",
                verbose_name="To region",
            ),
        ),
    ]
