# Generated by Django 5.2.8 on 2025-12-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0036_alter_publictransport_fromregion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publictransport",
            name="transportType",
            field=models.CharField(
                choices=[
                    ("BUS", "Bus"),
                    ("METRO", "Metro"),
                    ("SUBWAY", "Subway"),
                    ("TRAIN", "Train"),
                    ("TRAM", "Tram"),
                ],
                default="BUS",
                max_length=10,
            ),
        ),
    ]
