# Generated by Django 5.2.8 on 2025-12-20 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0037_publictransport_transporttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Transport Type",
                "verbose_name_plural": "Transport Types",
            },
        ),
        migrations.AlterField(
            model_name="publictransport",
            name="transportType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_transports",
                to="guard.transporttype",
                verbose_name="Transport Type",
            ),
        ),
    ]
