# Generated by Django 5.2.8 on 2025-12-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0038_transporttype_alter_publictransport_transporttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="transporttype",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transporttype",
            name="name_fr",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publictransport",
            name="transportType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_transports",
                to="guard.transporttype",
                verbose_name="Transport Type",
            ),
        ),
    ]
