# Generated by Django 5.2.8 on 2025-12-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0039_transporttype_name_en_transporttype_name_fr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publictransport",
            name="transportType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_transports",
                to="guard.transporttype",
                verbose_name="Transport Type",
            ),
        ),
    ]
