# Generated by Django 5.2.8 on 2025-12-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0040_alter_publictransport_transporttype"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransportType",
            new_name="PublicTransportType",
        ),
        migrations.AlterModelOptions(
            name="publictransporttype",
            options={
                "verbose_name": "Public Transport Type",
                "verbose_name_plural": "Public Transport Types",
            },
        ),
        migrations.RemoveField(
            model_name="publictransport",
            name="transportType",
        ),
        migrations.AddField(
            model_name="publictransport",
            name="publicTransportType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_transports",
                to="guard.publictransporttype",
                verbose_name="Public Transport Type",
            ),
        ),
    ]
