# Generated by Django 5.2.8 on 2025-12-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0041_rename_transporttype_publictransporttype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tip",
            name="location",
        ),
    ]
