# Generated by Django 5.2.8 on 2025-12-22 08:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0042_remove_tip_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="tip",
            name="description_en",
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name="tip",
            name="description_fr",
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
