# Generated by Django 5.2.8 on 2025-12-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0043_alter_tip_description_alter_tip_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tip",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="tip",
            name="description_fr",
            field=models.TextField(null=True),
        ),
    ]
