# Generated by Django 5.2.8 on 2025-12-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0045_alter_tip_description_alter_tip_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "image",
                    models.ImageField(upload_to="partners/", verbose_name="Image"),
                ),
                ("link", models.URLField(verbose_name="Link")),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
    ]
