# Generated by Django 5.2.9 on 2025-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0047_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weekday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "Sunday"),
                            (2, "Monday"),
                            (3, "Tuesday"),
                            (4, "Wednesday"),
                            (5, "Thursday"),
                            (6, "Friday"),
                            (7, "Saturday"),
                        ],
                        unique=True,
                        verbose_name="Day",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekday",
                "verbose_name_plural": "Weekdays",
                "ordering": ["day"],
            },
        ),
        migrations.AddField(
            model_name="location",
            name="openDays",
            field=models.ManyToManyField(
                blank=True,
                related_name="locations",
                to="guard.weekday",
                verbose_name="Open Days",
            ),
        ),
    ]
