# Generated by Django
from django.db import migrations


def populate_weekdays(apps, schema_editor):
    Weekday = apps.get_model("guard", "Weekday")
    # 1=Sunday, 2=Monday, ... 7=Saturday
    # These match the IntegerChoices values in models.py
    for i in range(1, 8):
        Weekday.objects.get_or_create(day=i)


class Migration(migrations.Migration):
    dependencies = [
        ("guard", "0048_weekday_location_opendays"),
    ]

    operations = [
        migrations.RunPython(populate_weekdays),
    ]
