# Generated by Django 5.2.9 on 2026-01-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0049_populate_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="publictransport",
            name="busNumber",
            field=models.CharField(
                default=18, max_length=255, verbose_name="Bus number"
            ),
            preserve_default=False,
        ),
    ]
