# Generated by Django 5.2.9 on 2026-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0050_publictransport_busnumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="openDays",
            new_name="closedDays",
        ),
    ]
