# Generated by Django 5.2.9 on 2026-01-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0051_rename_opendays_location_closeddays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="closedDays",
            field=models.ManyToManyField(
                blank=True,
                related_name="locations",
                to="guard.weekday",
                verbose_name="Closed Days",
            ),
        ),
    ]
