# Generated by Django 5.2.9 on 2026-01-05 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0052_alter_location_closeddays"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hiking",
            name="location",
        ),
        migrations.AddField(
            model_name="hiking",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="hiking",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.CreateModel(
            name="HikingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "hiking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guard.hiking"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guard.location"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("hiking", "location")},
            },
        ),
        migrations.AddField(
            model_name="hiking",
            name="locations",
            field=models.ManyToManyField(
                through="guard.HikingLocation",
                to="guard.location",
                verbose_name="Location",
            ),
        ),
    ]
