# Generated by Django 5.2.9 on 2026-01-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        ("guard", "0053_remove_hiking_location_hiking_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="cities_light.country",
                verbose_name="Country",
            ),
        ),
    ]
