# Generated by Django 5.2.9 on 2026-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guard", "0054_ad_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="boost",
            field=models.BooleanField(default=False),
        ),
    ]
